### ISSUE TITLE
OpenJDK 11 failure - running tests or application

### ISSUE THREAD

**Issue by practicalli-johnny** [CircleCI-Public/circleci-demo-clojure-luminus#2]
Using `lein run` or `lein test` when using OpenJDK 11 on Ubuntu Linux 20.04 fails.  Leiningen version 2.9.1.

On the same machine with OpenJDK 8 the tests and application run.

Here is the start of the stack trace when using OpenJDK 11
```
$ lein test
Warning: implicit hook found: lein-cprop.plugin/hooks
Hooks are deprecated and will be removed in a future version.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray, compiling:(flatland/ordered/set.clj:19:1)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
```

I am not concerned about having the example project fixed for OpenJDK 11, however, would like to inform others that this project only seems to work for OpenJDK 8 so they will use an appropriate image.

Thank you.

**Comment by practicalli-johnny** [comment]
Using the `openjdk-8-lein-2.9.3` image in the configuration for this project will run successful builds.

```
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.3

```
